app/models/__init__.py
from app.models.category import Category
from app.models.post import Post

app/models/category.py
from app import db

# Modelo Categoria
class Category(db.Model):
    __tablename__ = 'categories'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False, unique=True)

app/models/post.py
from app import db

# Modelo Post
class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text, nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('categories.id'), nullable=True)
    category = db.relationship('Category', backref=db.backref('posts', lazy=True))

app/__init__.py
import os
from flask import Flask, request, jsonify, render_template, redirect, url_for
from flask_sqlalchemy import SQLAlchemy

from dotenv import load_dotenv

#Cargar las variables de entorno
load_dotenv()

#Crear instancia
app = Flask(__name__)

#Configuración de la base de datos PostgreSQL
app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

# Inicializar SQLAlchemy
db = SQLAlchemy(app)

#Importar modelos para que SQLAlchemy los reconozca
from app.models import Post
from app.models import Category

# Crear las tablas si no existen
with app.app_context():
    db.create_all()

#Importar y registrar los Blueprints
from app.routes.post import posts_bp
from app.routes.category import categories_bp

app.register_blueprint(posts_bp, url_prefix='/posts')
app.register_blueprint(categories_bp, url_prefix='/categories')

#Ruta principal: home
@app.route('/')
def index():
    #return 'Hola mundo'
    return render_template('index.html')

app/routes/category.py
from flask import Blueprint, render_template, redirect, request, url_for
from app import db
from app.models import Post
from app.models import Category

categories_bp = Blueprint('categories', __name__)

#Listar las categorias
@categories_bp.route('/')
def listar_categories():
    categories = Category.query.all()
    return render_template('categories/listar_categories.html', categories=categories)

#Crear las categorias
@categories_bp.route('/new', methods=['GET','POST'])
def add_category():
    if request.method == 'POST':
        name = request.form['name']
        new_category = Category(name=name)
        db.session.add(new_category)
        db.session.commit()
        return redirect(url_for('categories.listar_categories'))
    #Aqui si es GET
    return render_template('categories/create_category.html')

@categories_bp.route('/update/<int:id>', methods=['GET','POST'])
def update_category(id):
    category = Category.query.get(id)
    if request.method == 'POST':
        category.name = request.form['name']
        db.session.commit()
        return redirect(url_for('categories.listar_categories'))
    #Aqui si es GET
    return render_template('categories/update_category.html', category=category)

@categories_bp.route('/delete/<int:id>')
def delete_category(id):
    category = Category.query.get(id)
    if category:
        db.session.delete(category)
        db.session.commit()
    return redirect(url_for('categories.listar_categories'))

app/routes/post.py
from flask import Blueprint, render_template, redirect, request, url_for
from app import db
from app.models import Post
from app.models import Category

posts_bp = Blueprint('posts', __name__)

@posts_bp.route('/')
def listar_posts():
    posts = Post.query.all()
    categories = Category.query.all()
    return render_template('posts/listar_posts.html', posts=posts, categories=categories)

@posts_bp.route('/new', methods=['GET','POST'])
def add_post():
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']    
        category_id = request.form.get('category_id')
        new_post = Post(title=title, content=content, category_id=category_id)
        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for('posts.listar_posts'))
    #Aqui si es GET
    categories = Category.query.all()
    return render_template('posts/create_post.html', categories=categories)

@posts_bp.route('/update/<int:id>', methods=['GET','POST'])
def update_post(id):
    post = Post.query.get(id)
    if request.method == 'POST':
        post.title = request.form['title']
        post.category_id = request.form['category_id']
        post.content = request.form['content']
        db.session.commit()
        return redirect(url_for('posts.listar_posts'))
    #Aqui si es GET
    categories = Category.query.all()
    return render_template('posts/update_post.html', post=post, categories=categories)

@posts_bp.route('/delete/<int:id>')
def delete_post(id):
    post = Post.query.get(id)
    if post:
        db.session.delete(post)
        db.session.commit()
    return redirect(url_for('posts.listar_posts'))

app/templates/base.html
<!DOCTYPE html>
<html class="theme-light" style="background-color: gainsboro;">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/ee9903c79f.js" crossorigin="anonymous"></script>
</head>
  <body >
    <header>
        <br>
        <h1 class="title has-text-centered is-1">Blog de Noticias</h1>
        <h2 class="subtitle has-text-centered is-4">Lo más reciente en México</h2>
        <hr>
    </header>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
  </body>
</html>

app/templates/categories/create_category.html
{% extends 'base.html' %}
{% block title%} Blog de Noticias{% endblock %}
{% block content%}
<div class="columns">
    <div class="column is-offset-3 is-6">
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">Agregar Category</p>
                    </div>
                </div>
                <div class="content">
                    <form action="{{ url_for('categories.add_category') }}" method="post">
                        <div class="field">
                            <label class="label">Nombre:</label>
                            <div class="control">
                                <input class="input" type="text" name='name'>
                            </div>
                        </div>
                        <button class="button is-success " type="submit">Agregar</button>
                        <a class="button is-danger" href="{{ url_for('categories.listar_categories') }}">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

app/templates/categories/listar_categories.html
{% extends 'base.html' %}
{% block title%} Blog de Noticias{% endblock %}
{% block content%}
<div class="columns">
    <div class="column is-offset-3 is-6">
		    <a  href="{{ url_for('categories.add_category') }}" class="button is-success"><i class="fa-solid fa-plus"></i> &nbsp; Agregar categoria</a>
        <br><br>        
        {% for category in categories %}
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">{{ category.name }}</p>
                    </div>
                </div>
                <a href="{{ url_for('categories.update_category', id = category.id )}}" class="button is-small is-link is-outlined"><i class="fa-solid fa-pen-to-square"></i></a>
                <a href="{{ url_for('categories.delete_category', id = category.id )}}" class="button is-small is-danger is-outlined"><i class="fa-solid fa-trash"></i></a>    
            </div>            
        </div>
        {% endfor %}
    </div>
</div>
{% endblock%}

app/templates/categories/update_category.html
{% extends 'base.html' %}
{% block title%} Blog de Noticias{% endblock %}
{% block content%}
<div class="columns">
    <div class="column is-offset-3 is-6">
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">Actualizar Category</p>
                    </div>
                </div>
                <div class="content">
                    <form action="{{ url_for('categories.update_category', id = category.id) }}" method="post">
                        <div class="field">
                            <label class="label">Nombre:</label>
                            <div class="control">
                                <input class="input" type="text" name='name' value="{{category.name}}">
                            </div>
                        </div>
                        <button class="button is-success " type="submit">Actualizar</button>
                        <a class="button is-danger" href="{{ url_for('categories.listar_categories') }}">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

app/templates/index.html
{% extends 'base.html' %}
{% block title%} Blog de Noticias{% endblock %}
{% block content%}
<div class="columns">
    <div class="column is-offset-3 is-6">
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">Posts</p>
                        <p class="subtitle is-5">Listar, Crear, Actualizar, Eliminar</p>
                    </div>
                </div>
                <a  href="{{ url_for('posts.listar_posts') }}" class="button is-success">IR</a>
            </div>            
        </div>
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">Categorias</p>
                        <p class="subtitle is-5">Listar, Crear, Actualizar, Eliminar</p>
                    </div>
                </div>
                <a  href="{{ url_for('categories.listar_categories') }}" class="button is-success">IR</a>
            </div>            
        </div>
    </div>
</div>
{% endblock%}

app/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title%} Blog de Noticias{% endblock %}
{% block content%}
<div class="columns">
    <div class="column is-offset-3 is-6">
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">Agregar Post</p>
                    </div>
                </div>
                <div class="content">
                    <form action="{{ url_for('posts.add_post') }}" method="post">
                        <div class="field">
                            <label class="label">Titulo:</label>
                            <div class="control">
                                <input class="input" type="text" name='title'>
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">Categoria:</label>
                            <div class="control">
                                <div class="select">
                                    <select name="category_id">
                                        {% for category in categories %}
                                        <option value="{{ category.id }}">{{ category.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">Contenido:</label>
                            <div class="control">
                                <textarea class="textarea" name="content"></textarea>
                            </div>
                        </div>
                        <button class="button is-success " type="submit">Agregar</button>
                        <a class="button is-danger" href="{{ url_for('posts.listar_posts') }}">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

app/templates/posts/listar_posts.html
{% extends 'base.html' %}
{% block title%} Blog de Noticias{% endblock %}
{% block content%}
<div class="columns">
    <div class="column is-offset-3 is-6">
		    <a  href="{{ url_for('posts.add_post') }}" class="button is-success"><i class="fa-solid fa-plus"></i> &nbsp; Agregar noticia</a>
        <br><br>        
        {% for post in posts %}
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">{{ post.title }}</p>
                        <p class="subtitle is-5">{{ post.category.name }}</p>
                    </div>
                </div>
                <div class="content">
                    {{ post.content }}
                </div>
                <a href="{{ url_for('posts.update_post', id = post.id )}}" class="button is-small is-link is-outlined"><i class="fa-solid fa-pen-to-square"></i></a>
                <a href="{{ url_for('posts.delete_post', id = post.id )}}" class="button is-small is-danger is-outlined"><i class="fa-solid fa-trash"></i></a>    
            </div>            
        </div>
        {% endfor %}
    </div>
</div>
{% endblock%}

app/templates/posts/update_post.html
{% extends 'base.html' %}
{% block title%} Blog de Noticias{% endblock %}
{% block content%}
<div class="columns">
    <div class="column is-offset-3 is-6">
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">Actualizar Post</p>
                    </div>
                </div>
                <div class="content">
                    <form action="{{ url_for('posts.update_post', id = post.id) }}" method="post">
                        <div class="field">
                            <label class="label">Titulo:</label>
                            <div class="control">
                                <input class="input" type="text" name='title' value="{{post.title}}">
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">Categoria:</label>
                            <div class="control">
                                <div class="select">
                                    <select name="category_id">
                                        {% for category in categories %}
                                        <option value="{{ category.id }}" {% if category.id == post.category_id %}selected{% endif %}>
                                            {{ category.name }}
                                        </option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">Contenido:</label>
                            <div class="control">
                                <textarea class="textarea" name="content" >{{post.content}}</textarea>
                            </div>
                        </div>
                        <button class="button is-success " type="submit">Actualizar</button>
                        <a class="button is-danger" href="{{ url_for('posts.listar_posts') }}">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}